#!/usr/bin/env bash
# ============================================================
#  clean.sh — clean (Linux/macOS)
#  Usage: bash clean.sh [--no-pause]
# ============================================================

set -euo pipefail
cd "$(dirname "$0")"

echo ""
echo "Cleaning previous build artifacts..."
rm -rf -- \
  node_modules \
  dist \
  dist-ssr \
  dist-portable \
  release \
  build \
  out \
  coverage \
  htmlcov \
  test-results \
  playwright-report \
  logs \
  .cache \
  .parcel-cache \
  .turbo \
  .webpack \
  .vite \
  .vite-temp \
  .nyc_output \
  .npm \
  .pnpm-store \
  .yarn-cache \
  .next \
  .nuxt \
  .svelte-kit \
  playwright/.cache \
  public/excalidraw-assets \
  src-tauri/target \
  src-tauri/gen \
  src-tauri/WixTools

# Extracted 7z fixture outputs under scripts/fixtures/ (disposable, gitignored).
# The committed .7z archives and the tracked docs-sync-check corpus are kept —
# only the extract-on-demand dirs are removed (regenerated by the test suite
# via scripts/fixture-lc-archives.mjs).
find scripts/fixtures -mindepth 1 -maxdepth 1 -type d ! -name 'docs-sync-check' -exec rm -rf {} +

# Generated files inside tracked source directories. Keep public/icons and the
# src-tauri/resources/.gitignore placeholder intact.
rm -f -- \
  src-tauri/resources/models-cache.json \
  src-tauri/resources/models-dev.json \
  src-tauri/resources/spine-builder.html \
  src-tauri/resources/LICENSE \
  src-tauri/resources/NOTICE \
  src-tauri/resources/THIRD_PARTY_LICENSES.md \
  THIRD_PARTY_LICENSES.md \
  legal/EXCALIDRAW_FONTS_LICENSES.md \
  src-tauri/cargo_check.txt \
  .eslintcache \
  .stylelintcache \
  .prettiercache \
  junit.xml \
  .dev-*.out \
  .build-*.out \
  .tauri-*.out \
  ./*.lcov \
  npm-debug.log* \
  yarn-debug.log* \
  yarn-error.log* \
  pnpm-debug.log*

find . -type f \( -name '*.tsbuildinfo' -o -name '*.log' -o -name '*.log.*' \) -delete

# Intentionally retained: LICENSE and NOTICE are source legal files.
echo "       Done."

echo ""
echo "============================================================"
echo " CLEAN SUCCESSFUL"
echo "============================================================"

if [[ "${1:-}" != "--no-pause" && -t 0 ]]; then
  read -r -p "Press Enter to close..."
fi
