/**
 * JS-side tool types.
 *
 * Separate from `src/modules/llm-client/types.ts` because these carry the runtime
 * concerns (zod schemas and execution logic) that the
 * wire format doesn't know about. The mapper in `registry.ts`
 * (`materialize()`) takes a `ToolHandler[]` and projects it to
 * `ToolDefinition[]` for the wire.
 */
import type { z } from 'zod';
import type { JsonSchema, TextPart, ImageUrlPart } from '../llm-client/types';
import type { SandboxBridge } from './sandbox-bridge';
import type { ResolvedSearchProvider } from './search-provider';
import type { AskUserInteraction } from './ask-user';
import type { ProfileRequestHeader, WhiteboardTurnReferences } from '../../types';

// ═══════════════════════════════════════════════════════════════════
// Phase 2.1 — Execution-group identity
// ═══════════════════════════════════════════════════════════════════

/**
 * Identity that links every model tool call to its native child
 * operations. One group per model tool call; one operation per
 * native child (shell process, web request, image analysis request,
 * research sub-request, etc.).
 *
 * Compound tools like `lc_web_research` register all child
 * operations under the same `groupId` so a single chat abort
 * cancels every sub-operation at once.
 *
 * Per Phase 2.1 — GPT §3.5, §6.2; DeepSeek C2.
 */
export interface ToolExecutionIdentity {
  /** Logical model tool call group. Shared by all native children of
   *  one model turn (e.g. one `lc_web_research` spawns 3 fetches —
   *  all 3 share the same groupId). */
  groupId: string;
  /** Unique per-child operation. Every native IPC call gets its own
   *  operationId so Rust can abort individual children within a
   *  compound tool that has partial success. */
  operationId: string;
  /** The provider-assigned tool call ID from the model stream
   *  (e.g. `call_abc123`). Persisted in store state for traceability. */
  modelToolCallId: string;
  /** The conversation this call belongs to. Enables cross-conversation
   *  registry cleanup and per-conversation cancellation scoping. */
  conversationId: string;
  /** The generation this call belongs to. A conversation ID alone cannot
   *  distinguish a call from a replacement generation started after a Retry
   *  or Stop, so prompt fencing, deduplication keys, image-batch cleanup, and
   *  audit records all need this to decide whether a late result still has an
   *  owner. Empty only for the placeholder identity built for contexts that
   *  never reach a model tool call. */
  generationId: string;
}

/** Board state visible to one active model turn. */
export interface WhiteboardToolSnapshot {
  refs: WhiteboardTurnReferences;
  /** Content from the user version pinned when the turn began. */
  userMarkdown: string;
  /** Latest retained or provisional model content in this turn. */
  modelMarkdown: string;
}

/** Authoritative state after a requested model-board replacement. */
export interface WhiteboardToolMutationState {
  refs: WhiteboardTurnReferences;
  changed: boolean;
  modelMarkdown: string;
}

/** Storage/lifecycle failures that the pure handler can expose stably. */
export type WhiteboardToolServiceErrorCode =
  | 'whiteboard_not_initialized'
  | 'whiteboard_version_missing'
  | 'whiteboard_read_failed'
  | 'whiteboard_write_failed'
  | 'aborted';

export type WhiteboardToolServiceResult<T> =
  | { ok: true; value: T }
  | { ok: false; code: WhiteboardToolServiceErrorCode };

/**
 * Turn-bound capability used by lc_whiteboard.
 *
 * The orchestrator owns IndexedDB and generation lifecycle details. The tool
 * receives only this small service so its schema, edit rules, and diagnostics
 * remain pure and independently testable.
 */
export interface WhiteboardToolService {
  read(input: { signal: AbortSignal }): Promise<WhiteboardToolServiceResult<WhiteboardToolSnapshot>>;
  replaceModel(input: {
    content: string;
    toolCallId: string;
    signal: AbortSignal;
  }): Promise<WhiteboardToolServiceResult<WhiteboardToolMutationState>>;
}

/** Context handed to every tool's `run` call. */
export interface ToolHandlerContext {
  /** Typed, testable bridge for all native tool commands. */
  sandbox: SandboxBridge;
  /** Per-conversation settings snapshot (timeout caps, allowed roots, etc.). */
  config: ToolConfig;
  /**
   * Abort signal. Mirrors the chat's AbortController. Tools should
   * forward it to any long-running work (the run_shell and web_fetch
   * handlers do this through the abort_tool_calls Tauri command).
   */
  signal: AbortSignal;
  /**
   * Phase 2.1: Execution-group identity for this tool call.
   * Links provider call IDs to native children for cancellation,
   * tracing, and result correlation. Present for every exposed
   * tool call — generated by the orchestrator before that call executes.
   */
  identity: ToolExecutionIdentity;
  /** Native preflight digest for compound mutations such as apply_patch. */
  nativePlanId?: string;
  /** Ask the user through the generation-owned modal interaction bridge. */
  askUser?: AskUserInteraction;
  /** Turn-bound conversation Whiteboard service, present only when exposed. */
  whiteboard?: WhiteboardToolService;
  /**
   * Call the LLM for sub-agent tasks (image analysis, research
   * synthesis, etc.). Tools use this to offload token-heavy work
   * to a separate model call, keeping base64 and large text
   * payloads out of the main conversation context.
   *
   * Only present when the chat has an active server profile;
   * undefined in environments without LLM access (tests, etc.).
   */
  llmCall?: (params: {
    /** System prompt for the sub-agent call. */
    systemPrompt: string;
    /** User message — plain text or multimodal (text + image_url parts). */
    userContent: string | Array<TextPart | ImageUrlPart>;
    /** Abort signal to cancel the sub-agent call. */
    signal: AbortSignal;
    /** Optional token cap for the sub-agent response. */
    max_tokens?: number;
    /**
     * Whether to request provider reasoning for this sub-agent call.
     * Defaults to true so existing callers retain their current behavior.
     * Providers may ignore this hint, so callers must still validate the
     * visible assistant output instead of treating it as a guarantee.
     */
    reasoningEnabled?: boolean;
    /** Optional provider reasoning effort override. Defaults to "medium". */
    reasoningEffort?: string;
    /** Optional model override. Falls back to the chat model if empty. */
    model?: string;
  }) => Promise<string>;
}

/** A registered, in-process tool that the model can call. */
export interface ToolHandler<I = unknown, O = unknown> {
  /** Stable name sent on the wire and used as the registry key. */
  name: string;
  /** Human-readable description shown to the model.  May be a static
   *  string or a function that returns a platform-aware string
   *  (e.g. run_shell adapts its description for Windows vs POSIX). */
  description: string | (() => string);
  /**
   * Optional one-liner for UI surfaces (e.g. the Tools panel). Falls
   * back to `description` if omitted. Prefer this for display — the
   * model gets full detail in `description`, but the user wants the
   * checkbox list dense, so keep this tight.
   */
  uiDescription?: string;
  /** Zod schema for the input object. Used to validate the wire args. */
  input: z.ZodType<I>;
  /**
   * Run the tool. Resolves with the output object, or throws on hard
   * failure. The runner catches the throw and converts it to a
   * `role: 'tool'` error message.
   */
  // Method syntax deliberately permits differently typed handlers to live in
  // the heterogeneous registry. The runner validates with each handler's own
  // Zod schema before invoking this method, so the erased registry boundary
  // does not bypass input validation.
  run(input: I, ctx: ToolHandlerContext): Promise<O>;
  /**
   * JSON Schema for the input object. Derived from `input` via
   * `z.toJSONSchema()` (Zod v4's built-in) and CACHED at module load
   * time. Called on every chat request that includes tools, so the
   * cache matters — 6 calls per request would otherwise re-derive
   * the schema tree 6 times.
   */
  toJsonSchema(): JsonSchema;
}

/**
 * Per-conversation tool settings. Lives on `Conversation.tools`
 * (top-level), not on `GenerationParams` (which is per-preset).
 */
export interface ToolConfig {
  /** Absolute paths the model is allowed to read/write/list. */
  allowedRoots: string[];
  /** Binary basenames the model is allowed to `run_shell`. */
  shellAllowlist: string[];
  /** Max `web_fetch` calls per minute per conversation. */
  webFetchRatePerMin: number;
  /** Hard cap on `run_shell` timeout, in milliseconds. */
  maxShellTimeoutMs: number;
  /** Hard cap on `web_fetch` response body, in bytes. */
  maxWebFetchBytes: number;
  /** Hard cap on `web_fetch` timeout, in milliseconds. */
  maxWebFetchTimeoutMs: number;
  /** Resolved search backend for `web_search` / `web_research`, with its
   *  credential. `null` = nothing configured, in which case the tools stay
   *  exposed and return NO_PROVIDER_MESSAGE — Web Access exposure is governed
   *  solely by `web_access_enabled`
   *  (docs/tools/TOOL-POLICY-MODEL.md §3.3), never by
   *  whether a credential happens to exist. Resolved per request from
   *  settings so switching provider takes effect mid-conversation.
   *  See `src/modules/tool-engine/search-provider.ts`. */
  searchProvider: ResolvedSearchProvider | null;
  /** Model for vision/image analysis (e.g. qwen/qwen3.6-27b).
   *  Falls back to llmModel if empty. */
  visionModel: string;
  /** Model for web research (e.g. qwen/qwen3.6-27b).
   *  Falls back to llmModel if empty. */
  webResearchModel: string;
  /** Model that summarizes PDF text for `lc_read_pdf`. Drives every summary
   *  call whose payload carries no page image; a chunk that does carry one
   *  goes to `visionModel`.
   *  Falls back to llmModel if empty. */
  pdfSummarizeModel: string;
  /** Base URL of the LLM server (for sub-agent calls). */
  llmServerUrl: string;
  /** Model name for sub-agent calls (e.g. vision model). */
  llmModel: string;
  /** API key for the LLM server (empty for local). */
  llmApiKey: string;
  /** API style for the LLM server: "chat" or "responses".
   *  Tools use this as fallback when the sub-agent model's own
   *  server profile can't be resolved (e.g. "Same as chat model"). */
  llmApiStyle: string;
  /** API variant for the LLM server: "openai", "anthropic", or "lm-studio".
   *  Tools use this as fallback when the sub-agent model's own
   *  server profile can't be resolved. */
  llmApiVariant: string;
  /** Request-header settings inherited from the active model profile. */
  llmIncludeLcIdentifierHeader?: boolean;
  llmLcIdentifierHeader?: ProfileRequestHeader;
  llmIncludeAdditionalRequestHeaders?: boolean;
  llmRequestHeaders?: ProfileRequestHeader[];
  /** True when the active chat model supports vision (image_url parts).
   *  Tools use this to short-circuit — e.g. lc_read_image analyze:false
   *  on a text-only model can warn immediately instead of reading the
   *  image and failing later. */
  modelIsVision?: boolean;
  /** The active conversation id. Used by lc_tool_history to query
   *  the conversation store for archived results. */
  convId?: string;
  /** Skill IDs currently enabled for the conversation. */
  skillIds?: string[];
  /** Authoritative tool exposure snapshot used by dynamic built-in guidance. */
  exposedToolNames?: string[];
  /** Custom skill definitions owned by the current conversation.
   *  Used by lc_skill to resolve non-built-in skill IDs (UUIDs). */
  customSkills?: import('../../types.ts').SkillDefinition[];

  // ═══════════════════════════════════════════════════════════════
  // Phase 2.5 — Per-call budgets (IPC-safe)
  // ═══════════════════════════════════════════════════════════════

  /**
   * Absolute monotonic deadline for this tool call, in milliseconds
   * (same epoch as `Date.now()`). Set once by the orchestrator at
   * call start. All sub-operations and native IPC calls derive their
   * timeout from this deadline using `remainingMs(deadlineMs)`.
   *
   * `undefined` means no budget is active (for example in a focused test).
   * When set, compound tools (web_research, batch reads) share this
   * single deadline — retries and sub-operation fan-out cannot
   * multiply the budget.
   */
  deadlineMs?: number;
}

/**
 * A tool call as we store it on the assistant message in the
 * conversation (the `Message` domain type in `src/types.ts`).
 *
 * Distinct from `ToolCallWire` (in `src/modules/llm-client/types.ts`) which is the
 * OpenAI-compat on-wire shape: `{ id, type: 'function', function: {
 * name, arguments: <json-string> } }`.
 */
export interface ToolCallRecord {
  id: string;
  name: string;
  arguments: string;
  // NOTE: there is deliberately no `status` field here. Execution state is
  // derived from the tool-result message (`tool_is_error`, `tool_duration_ms`)
  // and from live run state in the UI — a second copy on the call record would
  // only be a stale duplicate. Removed pre-1.0, when there was no persisted
  // data to stay compatible with; see data-model.md.
  /** Filled lazily by `validateToolCalls` after zod validation. */
  arguments_parsed?: unknown;
  created_at: number;
}

/**
 * A tool result as we store it on the follow-up `role: 'tool'`
 * message in the conversation.
 */
export interface ToolResultRecord {
  tool_call_id: string;
  output: string;
  is_error: boolean;
  duration_ms: number;
}

// ═══════════════════════════════════════════════════════════════════
// Phase 2.4 — Unified discriminated result envelope
// ═══════════════════════════════════════════════════════════════════

/**
 * Discriminated tool result status.
 * Replaces the `is_error` boolean with precise terminal states.
 *
 *   - `ok`: all sub-operations succeeded; data is complete.
 *   - `partial`: mixed batch — some items succeeded, some failed.
 *     The issues array carries per-item failure details.
 *   - `error`: all-item failure; no usable data.
 *   - `aborted`: cancelled by user before completion.
 *   - `timeout`: exceeded the per-call deadline.
 */
export type ToolStatus = 'ok' | 'partial' | 'error' | 'aborted' | 'timeout';

/**
 * A structured issue within a tool result.
 *
 * Phase 2.4 replaces string-scraping for paths and error codes
 * with explicit, machine-readable issue descriptors.
 */
export interface ToolResultIssue {
  /** Stable error/success code (e.g. 'path_outside_roots', 'too_large'). */
  code: string;
  /** Human-readable description for the model and user. */
  message: string;
  /** Affected path (file, dir, URL, etc.), if applicable. */
  path?: string;
  /** True only when repeating the same call may succeed without correction. */
  retryable?: boolean;
  /** Native OS error code retained from the launch boundary, when available. */
  native_code?: number | string;
  /** Native OS error text retained from the launch boundary, when available. */
  native_reason?: string;
  /** Executable involved in a launch failure, when applicable. */
  executable?: string;
  /** Machine-readable replacement input. It is never executed implicitly. */
  suggested_call?: Record<string, unknown>;
  /** One short action that can correct or terminate this failure. */
  remedy?: string;
  /** Exact arguments for detailed guidance about the affected tool. */
  help?: {
    tool: string;
    query: string;
  };
  /** Bounded alternatives for an unknown operational tool name. */
  suggestions?: Array<{
    tool: string;
    purpose: string;
  }>;
  /** Executable name that the corrected call must satisfy in the allowlist. */
  required_allowlist_entry?: string;
}

/**
 * Unified discriminated result envelope for all tool executions.
 *
 * Design contract (Phase 2.4, GPT §3.8):
 *   - Every tool result has exactly one `status`.
 *   - `issues` is empty for `ok`. Every other status identifies its issue.
 *   - Per-item errors in batch tools propagate truthfully.
 *   - Provider/network/protocol errors remain distinguishable
 *     from tool-logic errors.
 *   - String-scraping for `path_outside_roots` etc. is removed;
 *     callers consume `issues[].code` and `issues[].path` instead.
 */
export interface ToolResultEnvelope<T = unknown> {
  /** Discriminated terminal status. */
  status: ToolStatus;
  /** Tool output data. Present for `ok` and `partial`; absent for
   *  `error`, `aborted`, `timeout`. */
  data?: T;
  /** Structured issues. Empty only for `ok`. */
  issues: ToolResultIssue[];
  /** Non-blocking warnings (for example, truncated output). */
  warnings: string[];
  /** Optional execution metrics. */
  metrics?: {
    durationMs: number;
    bytesRead?: number;
    bytesWritten?: number;
  };
}

/**
 * Serialize a ToolResultEnvelope into the string that gets stored
 * as a `role: 'tool'` message. The model sees this JSON so it can
 * adapt to structured error codes on the next turn.
 *
 * Phase 2.4: Structured terminal results keep status and issue codes
 * together instead of making callers infer policy failures from strings.
 * Plain successful handler values remain supported as normal tool payloads.
 */
export function serializeEnvelope(env: ToolResultEnvelope): string {
  return JSON.stringify(env);
}

/**
 * Build a simple ok envelope from a tool's output value.
 */
export function okEnvelope<T>(data: T, durationMs: number, warnings?: string[]): ToolResultEnvelope<T> {
  return {
    status: 'ok',
    data,
    issues: [],
    warnings: warnings ?? [],
    metrics: { durationMs },
  };
}

/**
 * Build an error envelope with structured issues.
 */
export function errorEnvelope(
  issues: ToolResultIssue[],
  durationMs: number,
  warnings?: string[],
): ToolResultEnvelope<never> {
  return {
    status: issues.length === 0 ? 'error' : 'error',
    issues,
    warnings: warnings ?? [],
    metrics: { durationMs },
  };
}

/**
 * Build an aborted envelope.
 */
export function abortedEnvelope(durationMs: number): ToolResultEnvelope<never> {
  return {
    status: 'aborted',
    issues: [{ code: 'aborted', message: 'Operation cancelled by user.' }],
    warnings: [],
    metrics: { durationMs },
  };
}

/**
 * Build a timeout envelope.
 */
export function timeoutEnvelope(durationMs: number): ToolResultEnvelope<never> {
  return {
    status: 'timeout',
    issues: [{ code: 'timeout', message: 'Operation exceeded the time limit.' }],
    warnings: [],
    metrics: { durationMs },
  };
}
